In [3]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
data=pd.read_csv("/content/drive/MyDrive/Artificial_Intelligence_Engineering/AIA/1_Churn_Modelling.csv")

In [ ]:
# Business problem:-To find out whether customers will leave the bank or not.

In [6]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
## missing values check
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
data.Geography

0        France
1         Spain
2        France
3        France
4         Spain
         ...
9995     France
9996     France
9997     France
9998    Germany
9999     France
Name: Geography, Length: 10000, dtype: object

In [9]:
data.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [10]:
pd.get_dummies(data.Geography)

      France  Germany  Spain
0       True    False  False
1      False    False   True
2       True    False  False
3       True    False  False
4      False    False   True
...      ...      ...    ...
9995    True    False  False
9996    True    False  False
9997    True    False  False
9998   False     True  False
9999    True    False  False

[10000 rows x 3 columns]

In [11]:
pd.get_dummies(data.Gender)

      Female   Male
0       True  False
1       True  False
2       True  False
3       True  False
4       True  False
...      ...    ...
9995   False   True
9996   False   True
9997    True  False
9998   False   True
9999    True  False

[10000 rows x 2 columns]

In [12]:
# Converison of categorical data
Geography=pd.get_dummies(data.Geography)
Gender=pd.get_dummies(data.Gender)

In [13]:
Geography,Gender

(      France  Germany  Spain
 0       True    False  False
 1      False    False   True
 2       True    False  False
 3       True    False  False
 4      False    False   True
 ...      ...      ...    ...
 9995    True    False  False
 9996    True    False  False
 9997    True    False  False
 9998   False     True  False
 9999    True    False  False

 [10000 rows x 3 columns],
       Female   Male
 0       True  False
 1       True  False
 2       True  False
 3       True  False
 4       True  False
 ...      ...    ...
 9995   False   True
 9996   False   True
 9997    True  False
 9998   False   True
 9999    True  False

 [10000 rows x 2 columns])

In [14]:
data=pd.concat([data,Geography,Gender],axis=1)

In [15]:
data.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,France,Germany,Spain,Female,Male
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,True,False,False,True,False
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,False,False,True,True,False
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,True,False,False,True,False
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,True,False,False,True,False
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,False,False,True,True,False

In [16]:
data.drop(['Geography','Gender'],axis=1,inplace=True)

In [17]:
data.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,France,Germany,Spain,Female,Male
0,1,15634602,Hargrave,619,42,2,0.00,1,1,1,101348.88,1,True,False,False,True,False
1,2,15647311,Hill,608,41,1,83807.86,1,0,1,112542.58,0,False,False,True,True,False
2,3,15619304,Onio,502,42,8,159660.80,3,1,0,113931.57,1,True,False,False,True,False
3,4,15701354,Boni,699,39,1,0.00,2,0,0,93826.63,0,True,False,False,True,False
4,5,15737888,Mitchell,850,43,2,125510.82,1,1,1,79084.10,0,False,False,True,True,False

In [18]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited', 'France', 'Germany', 'Spain', 'Female',
       'Male'],
      dtype='object')

In [19]:
## Creating independent and dependent variable.
X=data.loc[:,['CreditScore', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary','France','Germany', 'Spain','Female', 'Male']]
y=data.Exited

In [20]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [21]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,France,Germany,Spain,Female,Male
0,619,42,2,0.00,1,1,1,101348.88,True,False,False,True,False
1,608,41,1,83807.86,1,0,1,112542.58,False,False,True,True,False
2,502,42,8,159660.80,3,1,0,113931.57,True,False,False,True,False
3,699,39,1,0.00,2,0,0,93826.63,True,False,False,True,False
4,850,43,2,125510.82,1,1,1,79084.10,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,True,False,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,True,False,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,True,False,False,True,False
9998,772,42,3,75075.31,2,1,0,92888.52,False,True,False,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,True,False,False,True,False

In [22]:
## Training and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=20)

In [23]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(7500, 13)
(7500,)
(2500, 13)
(2500,)

In [24]:
X_train

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,France,Germany,Spain,Female,Male
2294,591,33,9,131765.72,1,1,0,118782.06,True,False,False,False,True
2808,654,42,7,99263.09,1,1,1,67607.90,True,False,False,False,True
6480,679,24,6,114948.76,2,0,1,135768.25,True,False,False,True,False
9202,528,31,9,120962.59,1,1,0,5419.31,True,False,False,False,True
3111,623,42,1,149332.48,2,1,0,100834.22,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3915,686,43,2,134896.03,1,1,1,97847.05,False,True,False,False,True
9620,561,37,4,101470.29,1,0,1,88838.14,False,False,True,False,True
7068,699,54,3,111009.32,1,1,1,155905.79,False,True,False,True,False
7391,430,31,5,0.00,1,1,0,95655.16,True,False,False,False,True
4367,573,50,0,159304.07,1,0,1,155915.24,False,False,True,False,True

In [25]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
X_train

array([[-0.60390003, -0.57054921,  1.37625225, ..., -0.5818665 ,
        -0.91826179,  0.91826179],
       [ 0.04473598,  0.28882669,  0.68299603, ..., -0.5818665 ,
        -0.91826179,  0.91826179],
       [ 0.30213122, -1.42992512,  0.33636792, ..., -0.5818665 ,
         1.08901406, -1.08901406],
       ...,
       [ 0.50804742,  1.43466124, -0.70351641, ..., -0.5818665 ,
         1.08901406, -1.08901406],
       [-2.2615254 , -0.76152164, -0.01026019, ..., -0.5818665 ,
        -0.91826179,  0.91826179],
       [-0.78922461,  1.05271639, -1.74340074, ...,  1.71860727,
        -0.91826179,  0.91826179]])

In [ ]:
X_train.shape

In [ ]:
X_train

In [27]:
mydf = pd.DataFrame(X_train,columns=['CreditScore', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary','France','Germany', 'Spain','Female', 'Male'])
mydf = np.round(mydf,4)
mydf

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,France,Germany,Spain,Female,Male
0,-0.6039,-0.5705,1.3763,0.8898,-0.9108,0.6406,-1.0306,0.3345,1.0091,-0.5798,-0.5819,-0.9183,0.9183
1,0.0447,0.2888,0.6830,0.3690,-0.9108,0.6406,0.9703,-0.5576,1.0091,-0.5798,-0.5819,-0.9183,0.9183
2,0.3021,-1.4299,0.3364,0.6203,0.8081,-1.5612,0.9703,0.6306,1.0091,-0.5798,-0.5819,1.0890,-1.0890
3,-1.2525,-0.7615,1.3763,0.7167,-0.9108,0.6406,-1.0306,-1.6417,1.0091,-0.5798,-0.5819,-0.9183,0.9183
4,-0.2744,0.2888,-1.3968,1.1712,0.8081,0.6406,-1.0306,0.0216,-0.9910,1.7247,-0.5819,-0.9183,0.9183
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,0.3742,0.3843,-1.0501,0.9399,-0.9108,0.6406,0.9703,-0.0305,-0.9910,1.7247,-0.5819,-0.9183,0.9183
7496,-0.9128,-0.1886,-0.3569,0.4044,-0.9108,-1.5612,0.9703,-0.1875,-0.9910,-0.5798,1.7186,-0.9183,0.9183
7497,0.5080,1.4347,-0.7035,0.5572,-0.9108,0.6406,0.9703,0.9816,-0.9910,1.7247,-0.5819,1.0890,-1.0890
7498,-2.2615,-0.7615,-0.0103,-1.2214,-0.9108,0.6406,-1.0306,-0.0687,1.0091,-0.5798,-0.5819,-0.9183,0.9183
7499,-0.7892,1.0527,-1.7434,1.3310,-0.9108,-1.5612,0.9703,0.9818,-0.9910,-0.5798,1.7186,-0.9183,0.9183

In [29]:
print(np.mean(mydf["CreditScore"]))
print(np.std(mydf["CreditScore"]))

print(np.mean(mydf["Age"]))
print(np.std(mydf["Age"]))

-7.600000000034394e-07
0.9999988323903602
2.2133333333314907e-06
0.9999995380694435

In [ ]:
from keras.models import Sequential

In [ ]:
from tensorflow.keras.models import Sequential

In [30]:
## Sequential modelling and functional modelling
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout # used to prevent overfitting

In [31]:
# Defining the model
model=Sequential()

# Adding input layer to first hidden layer
model.add(Dense(units=16,input_dim=13,activation='relu',
                kernel_initializer='he_uniform'))

# Adding first hidden layer to second hidden layer
model.add(Dense(units=20,activation='relu',kernel_initializer='he_uniform'))

# Adding second hidden layer to third hidden layer
model.add(Dense(units=10,activation='relu',kernel_initializer='he_uniform'))

# Adding third hidden layer to output layer
model.add(Dense(units=1,activation='sigmoid',kernel_initializer = 'glorot_uniform'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 20)             │           340 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           210 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
weights, bias = model.layers[0].get_weights()

In [ ]:
type(weights)

In [ ]:
weights.shape

In [ ]:
pd.DataFrame(weights)

In [ ]:
sns.kdeplot(weights[:,4])

In [ ]:
pd.DataFrame(weights,index = ["{}st placeholder".format(i) for i in range(1,14)], columns=["{}st neuron".format(i) for i in range(1,17)])

In [ ]:
weights[:,0]

In [ ]:
from scipy import stats
print(stats.skew(weights[:,1]))
print(stats.kurtosis(weights[:,1]))

In [ ]:
import seaborn as sns
sns.kdeplot(weights[:,4])

In [ ]:
mydata = weights.reshape(-1)

In [ ]:
mydata

In [ ]:
import seaborn as sns
sns.kdeplot(mydata)

In [ ]:
...
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [ ]:
X_train.shape

In [ ]:
len(X_train)

In [ ]:
7500 - ((30/100)*7500)

In [ ]:
7500 - 5250

In [ ]:
# 5250 --> Training
# 2250 --> Validation

In [ ]:
5250/32

In [ ]:
X_train.shape

In [ ]:
(30/100)*7500

In [ ]:
7500 - 2250

In [ ]:
5250/32

In [ ]:
# fit the keras model on the dataset
model_history=model.fit(X_train, y_train, epochs=50,validation_split=0.30, batch_size=32)

In [ ]:
model_history.history.keys()

In [ ]:
print(model_history.history['loss'])

In [ ]:
import matplotlib.pyplot as plt
plt.plot(model_history.history['accuracy'],label='train_accuracy')
plt.plot(model_history.history['val_accuracy'],color='red',label='val_acc')
plt.legend()

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)

In [ ]:
print(y_pred)

In [ ]:
y_test

In [ ]:

y_pred

In [ ]:
y_pred.reshape(-1)

In [ ]:
mypred = [1 if prediction > 0.5 else 0 for prediction in y_pred.reshape(-1)]
print(mypred)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,mypred))

In [ ]:
abc

In [ ]:
## < 0.5 = 0
## >= 0.5 = 1

y_prediction = np.array([1 if i >= 0.5 else 0 for i in y_pred.reshape(2500,)])

In [ ]:
accuracy_score(y_test,abc)

In [ ]:
model.evaluate(X_test,y_test)

In [ ]:
...
# evaluate the keras model
accuracy = model.evaluate(X_test, y_test)
accuracy

In [ ]:
# list all data in history
print(model_history.history.keys())

In [ ]:
model_history.history

In [ ]:
# summarize history for accuracy
import matplotlib.pyplot as plt
plt.plot(model_history.history['accuracy'])
plt.plot(model_history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'])
plt.show()

In [ ]:
# summarize history for loss
plt.plot(model_history.history['loss'])
plt.plot(model_history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
#Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

In [ ]:
# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
score